// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI7pwYr7c1qXW_GRp-nukVwkK8MjMwybQ',
    appId: '1:547432855128:web:27cefd5b378f501a913c2d',
    messagingSenderId: '547432855128',
    projectId: 'barksite-33a0d',
    authDomain: 'barksite-33a0d.firebaseapp.com',
    storageBucket: 'barksite-33a0d.firebasestorage.app',
    measurementId: 'G-Y273F3736J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxvNkuyczhHMByt-G-xR5TnjIm7BYXYfQ',
    appId: '1:547432855128:android:7f042d0dd0934754913c2d',
    messagingSenderId: '547432855128',
    projectId: 'barksite-33a0d',
    storageBucket: 'barksite-33a0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOPqhcphlVCGivuoB8Wc8UPgPZT48KhtY',
    appId: '1:547432855128:ios:73bb28b34e2706ee913c2d',
    messagingSenderId: '547432855128',
    projectId: 'barksite-33a0d',
    storageBucket: 'barksite-33a0d.firebasestorage.app',
    iosBundleId: 'com.example.barkbitesApp',
  );
}
